name: weagus
description: A weather App project for DAM

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.13.3
  location: ^4.2.0
  intl: ^0.16.1
  flutter_dotenv: ^5.0.2
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#23898d"
  image: images/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
